name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.3
homepage: https://github.com/anicdh/bip39
author: anicdh <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  pointycastle:
  hex:
  crypto:
dev_dependencies:
  test: ^1.0.0
